package com.example.f1hub.data;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import android.content.Context;

public class DriverInfoRepo {

    private static DriverInfoRepo INSTANCE;

    private Context context;


    public static DriverInfoRepo getRepository(Context context){
        if (INSTANCE == null){
            synchronized (DriverInfoRepo.class){
                if(INSTANCE == null)
                    INSTANCE = new DriverInfoRepo();
                INSTANCE.context = context;
            }
        }
        return INSTANCE;
    }

    /**
     * returns a list of information generated by getDriverInformation
     * @param number information to return
     *
     * @return information to return
     */

    public List<DriverInfo> getDriverInformation(int number){
        List<DriverInfo> information = new ArrayList<>(number);
        for (int i = 0; i < number; i++){
            DriverInfo di = getDriverInformation();

            information.add(di);
        }
        return information;
    }

    public DriverInfo getDriverInformation (){
        // create a new obj
        DriverInfo di = new DriverInfo();

        // random number to populate for now
        Random random = new Random();
        int id = random.nextInt(1000);

        String name = "Lewis hammy";
        int points = 1;


        di.setDriverName(name + id);
        di.setDriverPoints(id + " Points");
        di.setDriverWins(id + " Wins");
        di.setDriverPos(id + " Place");

        return di;
    }
}
